Ext.define('ExtMVC.model.InvItem', {
    extend: 'Ext.data.Model',
    fields: ['id',
        'item_name',
        'alias_name',
        'group_id',
        'unit_id',
        'qty',
        'rate',
        'amount',        
        'other_tax_rate',
        'tax_rate',        
        'group_name',
        'group_code',
        'unit',
        'PurchaseAccount',
        'SalesAccount',
        'salesUnitId',
        'perUnit',
        'stock',
        'category_id',
        'category',
        'department_id',
        'department',
        'sales_rate',
        'purchase_rate',
        'sales_unit'
    ]
});