var Ext = Ext ||{};Ext.lang = {
  "global": {
    "langId":"0",
    "font":["Arial Narrow","Kalimati"],
    "fontsize":["10","10"],
    "pageNo":["Page No.","पाना नं."],
    "developerName":["WebPay Pvt. Ltd.","वेबपे प्रा.लि."],
    "developerAddress":["Sankhamul, Kathmandu","शंखमूलमार्ग, काठमाण्डाै"],
    "developerContactNo":["9841201980","९८४१२०१९८०"],
    "developerWebsite":["www.webpay.com.np","www.webpay.com.np"],
    "developerEmail":["mail@webpay.com.np","mail@webpay.com.np"],
    "branch":["Branch Office: Lahan, Siraha","शाखा कार्यालयः लहान, सिरहा"],
    "welcome":["Welcome","स्वागतम"],
    "fy":["Fiscal Year","अार्थिक बर्ष"],
    "companyname": ["WebPay","वेबपे"],
    "time": ["Time","समय"],
    "setup": ["Setup","सेटअप"],
    "mainMenu":["Main Menu","मरूख् मेनु"],
    "masterSetup":["Master Setup","मास्टर सेटअप"],
    "acSetup":["Account Seutp","एकाउन्ट सेटअप"],
    "voucherEntry":["Voucher Entry","भाैचर इन्टि"],
    "inventorySetup":["Inventory Setup","इन्भेन्ट्रि सेटअप"],
    "inventoryEntry":["Inventory Entry","इन्भेन्ट्रि इन्टि्र"],
    "appNature":["Business Management System (BMS)","बिजनेश व्यवस्थापन सिस्टम"],
    "appName": ["AccPack","एक्प्याक"],
    "code": ["Code","संकेत"],
    "coder": ["Code","संकेत"],
    "desc":["Description","बिवरण"],
    "status":["Status","स्थिति"],
    "printed":["Printed","मृद्रित"],
    "approved":["Approved","स्विकृत"],
    "yes":["Yes","हो"],
    "no":["No","होइन"],
    "cha":["Yes","छ"],
    "chaina":["No","छैन"],
    "add":["Add","नयाँ प्रबिष्टि"],
    "del":["Delete","मेट्ने"],
    "delete":["Delete","मेट्ने"],
    "edit":["Edit","सच्याउने"],
    "print":["Print","मुद्रण गर्ने"],
    "save":["Save","सुरक्षित गर्नुहोस्"],
    "close":["Close","बन्द गर्नुहोस्"],
    "cancel":["Cancel","रद्द गर्नुहोस्"],
    "approve":["Approve","स्विकृत गर्नुहोस्"],
    "amount":["Amount","रकम"],
    "checkPass":["Check Password","पासवर्ड चेकगर्नुहोस"],
    "changePass":["Change Password","पासवर्ड बदल्नुहोस"],
    "both":["Both","दुबै"],
    "active":["Active","सक्रिय"],
    "passive":["Passive","निस्क्रिय"],
    "search":["Search","खोज्नुहोस"], 
    "searchTitle":["Search","खोज"],
    "reset":["Reset","रिसट"],
    "male":["Male","पुरूष"],
    "female":["Female","महिला"],
    "sex":["Sex","लिंग"],
    "invalidAcNo":["Invalid Account No","गलत एकाउन्ट नम्बर"],
    "msgInvalidAcNo":["Please Enter Proper Account Number","कृपया सही एकाउन्ट नम्बर"],
    "dt":["Date (BS)","मिति"],
    "dtbs":["Date (BS)","मिति (बि.सं.)"],
    "entryTime":["Entry Time","इन्टि समय"],
    "ok":["Ok","ठीक छ"],
    "loginFailed":["Login Failed","ल्गइन सफल हुन सकेन"],
    "incorectUserOrPass":["Incorrect User Email or Password","गलत इमेल वा पासवर्ड"],
    "accountInactive":["Your account is not active","तपाइको एकाउन्ट एक्टिभ छैन"],
    "accountBlocked":["Your account is blocked by administrator","तपाइको एकाउन्ट ब्लक गरिएको छ"],
    "accountNo":["Account No","एकाउन्ट नं."],
    "accountDesc":["Account Desc.","एकाउन्ट बिवरण"],
    "address":["Address","ठेगाना"],
    "contactNo":["Contact No","सम्पर्क नं."],
    "email":["Email","इमेल"],
    "bs":["BS","बि.सं."],
    "ad":["AD","इ.सं."],
    "close":["Close","बन्दगर्नुहोस"],
    "prepare":["Prepare","तयार गर्नुहोस्"],
    "fromDt":["From","देखि"],
    "uptoDt":["Upto","सम्म"],
    "noVoucherFound":["Not Found","पाइएन"],
    "newVoucher":["New","नयाँ भाैचर"],
    "wantNewVoucher":["Do you want new voucher ?","के तपाइ नयाँ भाैचर चाहनुहुन्छ ?"],
    "user":["User","युजर"],
    "cash":["Cash","नगद"],
    "Credit":["Credit","क्रेडिट"],
    "Debit":["Debit","डेबिट"],
    "inWords":["In Words","अक्षरेपि"],
    "name":["Name","नाम"],
    "total":["Total","जम्मा"],
    "role":["Role","रोल"],
    "Inventory":["Inventory","इन्भेन्ट्रि"],
    "menumanager":["Menu Manager","मेनु म्यानेजर"],
    "changePassword":["Change Password","पासवर्ड बदल्नुहोस"],
    "createMultiAccount":["Create Remaining A/C","बाँकि एकाउन्ट पनि बनाउनुहोस"],
    "paymentVoucherCash":["Payment Voucher","भुक्तानी भाैचर"],
    "paymentVoucherBank":["Bank Payment Voucher","बैंक भुक्तानी भाैचर"],
    "receiptVoucherCash":["Receipt Voucher","प्राप्ती भाैचर"],
    "receiptVoucherBank":["Bank Receipt Voucher","बैंक प्राप्ती भाैचर"],
    "bankName":["Bank Name","बंकको नाम"],
    "savingAc":["Saving A/C","बचत खाता"],
    "fixedDepositAc":["Fixed Dep. A/C","मृद्दति खाता"],
    "currentAc":["Current A/C","चालु खाता"],
    "married":["Married","बिवादित"],
    "unmarried":["Unmarried","अबिवादित"],
    "preparedBy":["Prepared By","तयार गर्ने"],
    "checkedBy":["Checked By","चेक गर्ने"],
    "approvedBy":["Approved By","स्विकृत गर्ने"],
    "narration":["Narration","न्यारेशन"],
    "only":["only","मात्र"],
    "paidBy":["Paid By","भुक्तानी कर्ता"],
    "receivedBy":["Received By","प्रप्ता गर्ने"],
    "discount":["Discount","डिस्काउन्ट"],
    "submit":["Submit","सवमिट"],
    "sn":["SN","सि.नं."],
    "cashPaid":["Paid Amount","तिरिएको रकम"],
    "cashier":["Cashier","क्यासियर"],
    "sal":["Year","बर्ष"],
    "mahina":["Month","महिना"],
    "period":["Period","पेरियड"],
    "recordDeleted":["Record Deleted Successfully","रेकर्ड सफलतापुर्वक मेटियो"],
    "item":["Item","सामान"],
    "aliasName":["Alias Name","छोटकरी नाम"],
    "itemName":["Item Name","सामानको नाम"],
    "itemDetails":["Item Details","सामानको बिवरण"],
    "rate":["Rate","रेट"],
    "qty":["Qty","परिमान"],
    "unit":["Unit","युनिट"],
    "createMultiAccount":["Create Remaining A/C","बाँकि एकाउन्ट बनाउनुहोस"],
    "searchPanelTitle":["Search","खोज"],
    "reports": ["Reports","रिपोर्टस"],
    "alya":["Alya","अल्या"],
    "purchase_qty":["Pur.Qty","खरिद परिमान"],
    "sales_qty":["Sls.Qty","बिक्रि परिमान"],
    "stock_blance":["Stk.Balance","स्टर माैज्दात"],
    "billNo":["Bill No.","बिजक नं."],
    "productName":["AccPack","AccPack"],
    "account":["Account","एकाउन्ट"],
    "entry":["Entry","इन्टि"],
    "facts":["Facts","तथ्यहरू"],
    "vouchers":["Vouchers","भाैचर"],
    "financial":["Financial","बितिय"],
    "org":["Organization","संस्था"],
    "recentUpdates":["Recent Updates","ताजा अपडेट"]
  },
  "khanepaniBilling":{
    "menuTitle":["Khanepani Billing","खानेपानी बिलिंग"],
    "billing":{
      "monthlyBilling":["Monthly Billing","मासिक बिलिंग"],
      "individualBilling":["Individual Billing","व्यक्तिगत बिलिंग"],
      "prv_reading":["Prv. Reading","अघिल्लो रिडिंग"],
      "cur_reading":["Cur. Reading","हाल्को रिडिंग"],
      "consumer_unit":["Consumed Unit","युनिट"]
    }
  },
  "khanepani":{
    "menuTitle":["Khanepani Setup", "खानेपानी सेटअप"]
  },
  "receipt":{
    "menuTitle":["Receipt Voucher","प्राप्ती भाैचर"],
    "billPayment":["Bill Payment","बिल भुक्तानी"],
    "oldDues":["Old Dues","पुरानो बक्याैता"],
    "discountAmt":["Disc. Amount","डिस्काउन्ट रकम"],
    "fineAmt":["Fine Amount","जरिवाना रकम"],
    "prvPaidAmt":["Paid. Amount","तिरिएको रकम"],
    "balance":["Balance","ब्यालेन्स"],
    "netAmount":["Payable Amt","बाँकि रकम"],
    "balanceAmt":["Balance Amt","ब्यालेन्स रकम"],
    "receivedDate":["Receipt Date","प्राप्ती मिति"],
    "paymentAmt":["Payment Amt","भुक्तानी रकम"],
    "discountNar":["Disc.on Bill","बिलमा छुट"],
    "fineNar":["Fine on Delay","बिलम्ब शूल्क"],
    "process":["Process","प्रोसेस"],
    "depositor":["Depositor","डिपोजिटर"]
  },
  "consumer_connection_histry":{
      "menuTitle":["Khanepani Pipeline Status","खानेपानी पाइपलाइनको स्थिति"],
      "formTitle":["Pipeline Status","पाइपलाइनको स्थिति"]
  },
  "pipelinestatus":{
    "menuTitle":["Pipeline/Meter Status List","पाइप/मिटरको स्थिति सूची"],
    "formTitle":["Pipeline/Meter Description","पाइप/मिटरको बिवरण"],
    "statusDesc":["Pipeline/Meter Status","पाइप/मिटरको स्थिति"]
  },
  "consumer":{
    "menuTitle":["Consumer List","उपभोक्ताको सूची"],
    "formTitle":["Consumer Description","उपभोक्ताको बिवरण"],
    "consumer_name":["Consumer Name","उपभोक्ताको नाम"],
    "consumer_no":["Consumer No.","उपभोक्ता नं."],
    "occupation":["Occupation","पेशा"],
    "membership_date_bs":["Membership Date","सदस्यता मिति"],
    "citizenship_no":["Citizenship No","नागरिकता नं."],
    "citi_issued_district":["Citiz.Issued Dist.","नागरिकता लिएको जिल्ला"],
    "citi_issued_date":["Citiz.Issued Date","नागरिकता लिएको मिति"],
    "voter_id":["Voter No","भोटर नं."],
    "house_no":["House No","घर नं."],
    "prv":["Prv.","पुरानो"],
    "cur":["Curr.","हाल्को"],
    "district":["Curr.District","हाल्को जिल्ला"],
    "vdc_mpc":["Curr MPC/VDC","हाल्को गा.पा./न.पा."],
    "ward_no":["Curr. Ward No.","हाल्को वडा नं."],
    "prv_district":["Prv. District","पुरानो जिल्ला"],
    "prv_vdc_mpc":["Prv. MPC/VDC","पुरानो गा.पा./न.पा."],
    "prv_ward_no":["Prv.Ward No.","पुरानो वडा नं."],
    "marg_tole":["Marg/Tole","मार्ग/टोल"],
    "local_migrated_id":["Local/Migrated","स्थानिय/बसाइसराइ"],
    "local":["Local","स्थानिय"],
    "migrated":["Migrated","बसाइसराइ"],
    "consumer_type_id":["New/Transfered","नयाँ/नामसारी"],
    "meter_no":["Meter No.","मिटर नं."],
    "accountNo":["Account No","एकाउन्ट नं."],
    "father_name":["Father Name","बुवाको नाम"],
    "grand_father_name":["G.Father Name","बाजेको नाम"],
    "personalInfo":["Personal Info","व्यक्तिगत बिवरण"],
    "otherInfo":["Other Info","अन्य बिवरण"]
  },
  "alie":{
    "assets":["Assets","सम्पति"],
    "liabilities":["Liabilities","दायित्व"],
    "income":["Income","अाय"],
    "expenditure":["Expenditure","व्यय"],
    "actual_profit":["Profit","नाफा"],
    "actual_loss":["Loss","नोक्सान"]
  },
  "ledger":{
      "menuTitle":["Ledger","लेजर"],
      "formDesc":["Ledger","लेजर"],
      "dateBs":["Date","मिति"],
      "generateLedger":["Prepare","तयार गर्नुहोस्"],
      "dt":["Date","मिति"]
  },
  "menu":{
    "mainMenu":["Main Menu","मुख्य मेनु"],
    "subMenu":["Sub Menu","सब-मेनु"],
    "menu":["Menu","मेनु"]
  },
  "narration":{
    "cashPayment":["Cash Payment","नगद भुक्तानी"],
    "bankPayment":["Bank Payment","बैंक भुक्तानी"],
    "cashReceipt":["Cash Receipt","नगद प्राप्ती"],
    "bankReceipt":["Cheque Receipt","चेक प्राप्ती"],
    "cshPurchase":["Cash Purchase","नगद खरिद"],
    "bankPurchase":["Cheque Purchase","बैंक खरिद"],
    "creditPurchase":["Credit Purchase","उधारो खरिद"],
    "cashSales":["Cash Sales","नगद बिक्रि"],
    "creditSales":["Credit Sales","उधारो बिक्रि"],
    "discountIncome":["Discount on Purchase (Income)","खरिदमा छुट"],
    "curUnitIsLow":["Curr. Rediang is Below Previous Reading.","हाल्को रिडिंग अधिल्लो रिडिंग भन्दा कम छ"],
  },
  "amountUnit":{
    "kharab":[" Kharab"," खर्ब"],
    "arab":[" Arab"," अर्ब"],
    "karor":[" Karod"," करोड"],
    "lakh":[" Lakh"," लाख"],
    "hajar":[" Thausand"," हजार"],
    "saya":[" Hundred"," सय"],
    "rupaiya":[" Repese"," रूपैया"],
    "paisa":[" Paisa"," पैसा"],
  },

  "akshar":{
    "n1":[" One"," एक"],
    "n2":[" Two"," दुर्इ"],
    "n3":[" Three"," तीन"],
    "n4":[" Four"," चार"],
    "n5":[" Five"," पाँच"],
    "n6":[" Six"," छ"],
    "n7":[" Seven"," सात"],
    "n8":[" Eight"," अाठ"],
    "n9":[" Nine"," नाैं"],
    "n10":[" Ten"," दस"],
    "n11":[" Eleven"," एघार"],
    "n12":[" Twelve"," बा्ह"],
    "n13":[" Thirteen"," ते्ह"],
    "n14":[" Fourteen"," चाैध"],
    "n15":[" Fifteen"," पन्ध्र"],
    "n16":[" Sixteen"," सोह्र"],
    "n17":[" Seventeen"," सतर्ह"],
    "n18":[" Eighteen"," अठारह"],
    "n19":[" Nineteen"," उन्नाइस"],
    "n20":[" Twenty"," बीस"],
    "n21":[" Twenty One"," एक्कार्इस"],
    "n22":[" Twenty Two"," बाइस"],
    "n23":[" Twenty Three"," तेर्इस"],
    "n24":[" Twenty Four"," चाैबीस"],
    "n25":[" Twenty Five"," पच्चीस"],
    "n26":[" Twenty Six"," छबीस"],
    "n27":[" Twenty Seven"," सत्तार्इस"],
    "n28":[" Twenty Eight"," अठार्इस"],
    "n29":[" Twenty Nine"," उनन्तीस"],
    "n30":[" Thiry"," तीस"],
    "n31":[" Thiry One"," एकतिस"],
    "n32":[" Thiry Two"," बतिस"],
    "n33":[" Thiry Three"," तेतिस"],
    "n34":[" Thiry Four"," चाैतिस"],
    "n35":[" Thiry Five"," पैतिस"],
    "n36":[" Thiry Six"," छतिस"],
    "n37":[" Thiry Seven"," सैंतिस"],
    "n38":[" Thiry Eight"," अरतिस"],
    "n39":[" Thiry Nine"," उनन्चालिस"],
    "n40":[" Fourty"," चालिस"],
    "n41":[" Fourty One"," एकचालिस"],
    "n42":[" Fourty Two"," बयालिस"],
    "n43":[" Fourty Three"," त्रिचालिस"],
    "n44":[" Fourty Four"," चवालिस"],
    "n45":[" Fourty Five"," पैतालिस"],
    "n46":[" Fourty Six"," छयालिस"],
    "n47":[" Fourty Seven"," सतचालिस"],
    "n48":[" Fourty Eight"," अाठचालिस"],
    "n49":[" Fourty Nine"," उनन्चास"],
    "n50":[" Fifty"," पचास"],
    "n51":[" Fifty One"," एक्यावन्न"],
    "n52":[" Fifty Two"," वाउन्न"],
    "n53":[" Fifty Three"," त्रिपन"],
    "n54":[" Fifty Four"," चाैवन्न"],
    "n55":[" Fifty Five"," पचपन्न"],
    "n56":[" Fifty Six"," छपन्न"],
    "n57":[" Fifty Seven"," सन्तावन"],
    "n58":[" Fifty Eight"," अन्ठावन्न"],
    "n59":[" Fifty Nine"," उनन्साठी"],
    "n60":[" Sixty"," साठी"],
    "n61":[" Sixty One"," एकसठी"],
    "n62":[" Sixty Two"," बैसठी"],
    "n63":[" Sixty Three"," त्रीसठी"],
    "n64":[" Sixty Four"," चाैसठी"],
    "n65":[" Sixty Five"," पैसठी"],
    "n66":[" Sixty Six"," छैसठी"],
    "n67":[" Sixty Seven"," सरसठी"],
    "n68":[" Sixty Eight"," अरसठी"],
    "n69":[" Sixty Nine"," उनान्सतरी"],
    "n70":[" Seventy"," सतरी"],
    "n71":[" Seventy One"," एकहतर"],
    "n72":[" Seventy Two"," वहतर"],
    "n73":[" Seventy Three"," त्रिहतर"],
    "n74":[" Seventy Four"," चाैहतर"],
    "n75":[" Seventy Five"," पचहतर"],
    "n76":[" Seventy Six"," छैहतर"],
    "n77":[" Seventy Seven"," सतहतर"],
    "n78":[" Seventy Eight"," अठहतर"],
    "n79":[" Seventy Nine"," उनान्सी"],
    "n80":[" Eighty"," असी"],
    "n81":[" Eighty One"," एक्कासी"],
    "n82":[" Eighty Two"," वयासी"],
    "n83":[" Seventy Three"," त्रियासी"],
    "n84":[" Eighty Four"," चाैरासी"],
    "n85":[" Eighty Five"," पचासी"],
    "n86":[" Eighty Six"," छयासी"],
    "n87":[" Eighty Seven"," सतासी"],
    "n88":[" Eighty Eight"," अठासी"],
    "n89":[" Eighty Nine"," उनान्वे"],
    "n90":[" Ninety"," नव्वे"],
    "n91":[" Ninety One"," एकान्वे"],
    "n92":[" Ninety Two"," वयान्वे"],
    "n93":[" Ninety Three"," त्रियान्वे"],
    "n94":[" Ninety Four"," चाैरान्वे"],
    "n95":[" Ninety Five"," पन्चान्वे"],
    "n96":[" Ninety Six"," छयान्वे"],
    "n97":[" Ninety Seven"," सन्तान्वे"],
    "n98":[" Ninety Eight"," अन्ठान्वे"],
    "n99":[" Ninety Nine"," उनान्सय"],
  },
  "rights":{
    "all":["All","सबैं"],
    "view":["View","भ्यु"],
    "add":["Add","नयाँ प्रबिष्टि"],
    "edit":["Edit","सच्याउने"],
    "delete":["Delete","मेट्ने"],
    "print":["Print","मुद्रण"],
    "userMgmt":["User Mgmt","युजर व्यवस्थापन"]
  },
  "newVoucher":{
    "purchase":["Do you want new Purchase Voucher?","के तपाइ नयाँ खरिद भाैचर चाहनुहुन्छ ?"],
    "sales":["Do you want new Sales Voucher?","के तपाइ नयाँ बिक्रि भाैचर चाहनुहुन्छ ?"],
    "journal":["Do you want new Journal Voucher?","के तपाइ नयाँ जरनल भाैचर चाहनुहुन्छ ?"],
    "receipt":["Do you want new Receipt Voucher?","के तपाइ नयाँ प्राप्ती भाैचर चाहनुहुन्छ ?"],
    "payment":["Do you want new Payment Voucher?","के तपाइ नयाँ भुक्तानी भाैचर चाहनुहुन्छ ?"],
  },
  "btn":{
    "ok":["Ok","ठीक छ"]
  },
  "narration":{
    "cashPurchase":[" purchase on cash","नगद खरिद"],
    "creditPurchase":[" purchase on credit from "," बाट उधारो खरिद"],
    "discountIncome":["Discount Income","डिस्काउन्ट"],
    "cshPurchase":["Cash Purchase of Goods","नगद सामान खरिद"],
    "vatLiab":["VAT Payable","भ्याट"],
    "cashSales":[" sales on cash","नगद बिक्रि"],
    "creditSales":[" sales on credit to "," लाइ उधारो बिक्रि"],
    "discountExpenditure":["Discount Expenditure","डिस्काउन्ट"],
    "cshSales":["Cash Sales of Goods","नगद सामा बिक्रि"],
    "vatAsst":["VAT Received","भ्याट"],
  },
  "msg":{
    "blankMessage":["Compulsory To Fill","अनिवार्य प्रबिष्टि"],
    "deleteVoucher":["Confirm to delete this voucher?","यो भाैचर मेट्न सहमत हुनुहुन्छ ?"],
    "deleteRecord":["Confirm to delete this record ?","यो रेकर्ड मेट्न सहमत हुनुहुन्छ ?"],
    "successfullyDeleted":["Successfully Deleted","सफलतापुर्वक मेटियो"],
    "successfullySaved":["Successfully Saved.","सफलतापुर्वक सुरक्षित गरियो"],
    "doLogout":["Logout","लगअाउट"],
    "invalidAcNo":["Invalid Account Number","गलत खाता नम्बर"],
    "passChanged":["Password Changed Successfully","पासवर्ड सफलतापुर्वक परिवर्तन गरियो"],
    "currentpassnotmatched":["Password Not Matched","पासवर्ड मिलेन"],
    "bothpassnotsame":["New Password and Confirm Password  are not same","दुबै पासवर्ड उहि भएन"],
    "currentpassnotmatched":["Current Password  not matched","हाल्को पासवर्ड मिलेन"],
    "invalidItemId":["Invalid Item Id","गलग सामानको करोड"],
    "noCreditorSelected":["No. Creditor is selected.","कुनै पनि क्रेडिटर छानिएको छैन"],
    "noDebtorSelected":["No. Debtor is selected.","कुनै पनि डेव्टर छानिएको छैन"],
    "stockNotEnough":["Balance is not enough","ब्यालेन्स प्रयाप्त भएन"]
  },
  "error":{
    "blankAccountNo":["Blank Account Number, Please Fill and retry again","बैंक एकाउन्ट खालि छ"],
    "selectVoucher":["Want to modify or add new voucher","नयाँ भाैचर वा पुरानो सच्याउने ?"],
    "acNoNotSeleted":["Account Number is not selected. Please Select Proper Account Number","गलत खाता नम्बर छानिएको छ"],
    "notInEditMode":["You do not have access to edit this record.","यो रेकर्ड सच्याउने अधिकार दिइएको छैन"],
    "zeroBalanceEntry":["Can not save in zero balance transactiion","जिरो ब्यालेन्स कारोबार मान्य छैन"],
    "balanceNotEnough":["Cash Balance is not enough.","नगद प्रयाप्त छैन"],
  },
  "entry":{
    "entryNo":["Voucher No.","भाैचर नं."],
    "sourceCode":["Source Code","तथ्यांक श्रोत"],
  },
  "Acselection":{
    "menuTitle":["Account Selection","एकाउन्ट छनोट"],
    "formDesc":["Account Description","एकाउन्ट बिवरण"]
  },
  "Itemselection":{
    "menuTitle":["Item Selection","सामानको छनोट"],
    "formDesc":["Item Description","सामानको बिवरण"]
  },
  "login":{
    "menuTitle":["Security Door","सुरक्षा ढोका"],
    "user":["User","युजर"],
    "userEmail":["Email","इमेल"],
    "password":["Password","पासवर्ड"],
    "loginButton":["Login","लगइन"],
    "profile":["Profile","प्रोफाइल"],
    "changePassword":["Change Password","पासवर्ड परिवर्तन"],
    "tr_close":["Close Transaction","कारोबार बन्दगर्नुहोस"],
    "logout":["Logout","लगअाउट"]
  },
  "mainmenu":{
    "menuTitle":["Main Menu","मुख्य मेनु"],
    "master":{
      "menuTitle":["Setup", "सेटअप"],
      "org":{
        "menuTitle":["Organization","संस्था"],
        "formDesc":["Organization Description","संस्थाको बिवरण"],
        "orgName":["Org. Name","संस्थाको नाम"],
        "address":["Address","ठेगाना"],
        "contactNo":["Contact No","सम्पर्क नं."],
        "emailAddress":["Email Address","इमेल ठेगाना"],
        "regdNo":["Regd. No","दर्ता नं."],
      },
      "unit":{
        "menuTitle":["Unit List","युनिट सूची"],
        "unit":["Unit","युनिट"],
        "shortName":["Short Name","छोटकरी नाम"],
        "formDesc":["Unit Description","युनिट बिवरण"],
      },
      "invgroup":{
        "menuTitle":["Group List","सामानको समूह"],
        "groupCode":["Group","समूह संकेत"],
        "groupName":["Group Name","समूहको नाम"],
        "parentGroupName":["Parent Group","माथिल्लो समूह"],
        "formDesc":["Group Description","समुहको बिवरण"],
        "childGroup":["Sub Group","उप-समूह"]
      },
      "item":{
        "menuTitle":["Item List","सामानको सूची"],
        "formDesc":["Item Description","सामानको बिवरण"],
        "item_name":["Item Name","सामानको नाम"],
        "alias_name":["Short Name","छोटकरी नाम"],
        "tax_rate":["Tax Rate","करको दर"],
        "other_tax_rate":["Other Tax Rate","अन्य करको दर"],
        "qty":["Qty","परिमाण"],
        "rate":["Rate","दर"],
        "amount":["Amount","रकम"],
        "OpeningBalance":["Opening Bal","अोपनिङ ब्यालेन्स"],
        "purchase_rate":["Purchase Rate","खरिद दर"],
        "sales_rate":["Sales Rate","बिक्रि दर"],
        "stock_balance":["Stock Balance","स्टक माैज्दात"],
        "pur_unit":["Pur.Unit","खरिद युनिट"],
        "sls_unit":["Sales Unit","बिक्रि युनिट"],
        "category":["Product/Service","उत्पादन/सेवा"],
        "product":["Product","उत्पादन"],
        "service":["Service","सेवा"],
        "purchaseAc":["Purchase A/C","खरिद एकाउन्ट"],
        "salesAc":["Sales A/C","बिक्रि एकाउन्ट"],
        "purchaseRateSetup":["Purchase Rate Setup","खरिद दर सेटअप"],
        "salesRateSetup":["Sales Rate Setup","बिक्रि दर सेटअप"],
        "wholeSalesRateSetup":["Wholesale Sales Rate","होलसेल बिक्रि दर"],
        "effectiveDateBs":["Effective Date (BS)","लागु मिति (बि.सं.)"],
        "effectiveDateAd":["Effective Date (AD)","लागु मिति (इ.सं.)"],
        "discountRate":["Disc. Rate(%)","डिस्काउन्ट दर"],
        "discount":["Discount","डिस्काउन्ट रकम"],
      },

      
      "tranopener":{
        "menuTitle":["Transaction Open","कारोबार खुल्ला"],
        "openDate":["Tran. Open Date(BS)","खुल्ला मिति"],
        "openButton":["Open Transaction","खुल्ला गर्नुहोस्"],
        "invalidDateRatenge":["Invalid Date","गलत मिति"],
        "invalidDateRangeMsg":["Entered Transaction Date is not from current Fiscal Year","दिइएको कारोबार मिति यस अार्थिक बर्षको होइन"],
      },
      "fiscalyear":{
        "menuTitle":["Fiscal Year","अार्थिक बर्ष"],
        "formDesc":["Fiscal Year List","अार्थिक बर्ष सूची"],
        "fiscalyear":["Fiscal Year","अार्थिक बर्ष"],
        "startDateBs":["Start Date(BS)","शुरू मिति (बि.सं.)"],
        "startDateAd":["Start Date(AD)","शुरू मिति (इ.सं.)"],
        "endDateBs":["End Date(BS)","अन्तिम मिति (बि.सं.)"],
        "endDateAd":["End Date(AD)","अन्तिम मिति (इ.सं.)"],
      },
      "sourcecode":{
        "menuTitle":["Source Code Setting","श्रोत कोड सेटिङ्ग"],
        "sourcecode":["Source Code","श्रोत कोड"],
        "formDesc":["Source Code Description","श्रोत कोड बिवरण"],
        "sourcetype":["Source Type","श्रोतको किसिम"],
        "shortName":["Short Name","छोटकरी नाम"],
        "length":["Length","लम्बाइ"],
      },
      "employee":{
        "menuTitle":["Employee","कर्मचारी"],
        "emp":["Employee Setup","कर्मचारी सेटअप"],
        "empcode":["Emp.Code","कर्मचारी कोड"],
        "formDesc":["Employee Description","कर्मचारी बिवरण"],
        "empname":["Employee Name","कर्मचारीको नाम"],
        "post":["Post","पद"],
        "address":["Address","ठेगाना"],
        "mobileNo":["Mobile Number","मोवाइल नं."],
        "emailAddress":["Email Address","इमेल ठेगाना"],
      },
      "unit":{
        "menuTitle":["Unit List","युनिट सूची"],
        "unit":["Unit","युनिट"],
        "shortName":["Short Name","छोटकरी नाम"],
        "formDesc":["Unit Desc","युनिट बिवरण"]
      }
    },
    "acsetup":{
        "menuTitle":["Account Setup","लेखा सेटअप"],
        "acgroup":{
            "menuTitle":["Account Group","लेखा समूह"],
            "groupName":["Group Name","लेखा समूह"],
            "parentGroup":["Parent Group","माथिल्लो समूह"],
            "acFormat":["A/C Format","खाताको बनोट"],
            "acNature":["A/C Nature","लेखा प्रकृति"]
        },
        "accountsetup":{
            "menuTitle":["ac_desc","लेखा बिवरण"],
            "acGroup":["A/C Group","लेखा समूह"],
            "acCode":["A/C Number","खाता नम्बर"],
            "acDesc":["A/C Description","बिवरण"],
            "address":["Address","ठेगाना"],
            "contactNo":["Contact No","सम्पर्क नम्बर"],
            "emailAddress":["Email","इमेल ठेगाना"],
            "openingBalance":["Opening Balance","शुरूको व्यालेन्स"]
        }
    },
    "transaction":{
        "menuTitle":["Transaction","कारोबार"],
        "purchase":{
          "menuTitle":["Purchase Voucher","खरिद भाैचर"],
          "formDesc":["Search","खोज"],
          "billNo":["Pur.Bill No","खरिद बिजक नं."],
          "billType":["Pur.Bill Type","खरिदको किसिम"],
          "creditor":["Creditor","क्रेडिटर"],
          "RefNo":["Ref. No","रिफरेन्स नं."],
          "RefDate":["Ref. Date","रिफरेन्स मिति"],
          "purchaseOrderNo":["Pur.Order No","खरिद अादेश नं."],
          "Item":["Item","सामान"],
          "discount":["Discount","डिस्काउन्ट दर"],
          "discountAmt":["Discount Amt","डिस्काउन्ट रकम"],
          "totalCost":["Total Cost","जम्मा रकम"],
          "vat":["VAT (13%)","भ्याट (१३%)"],
          "netAmount":["Net Amount","नेट रकम"]
        },
        "purchasereturn":{
          "menuTitle":["Purchase Return Voucher","खरिद फिर्ता भाैचर"]
        },
        "salesreturn":{
          "menuTitle":["Sales Return Voucher","बिक्रि फिर्ता भाैचर"]
        },
        "wholesales":{
          "menuTitle":["Wholesale Voucher","होलसेल बिक्रि भाैचर"]
        },
        "production":{
          "menuTitle":["Production Voucher","उत्पादन भाैचर"]
        },
        "voucherlist":{
          "menuTitle":["Voucher List","भाैचर सूची"]
        },
        "sales":{
          "menuTitle":["Sales Voucher","बिक्रि भाैचर"],
          "formDesc":["Search","खोज"],
          "billNo":["Sales Bill No","बिक्रि बिल नं."],
          "billType":["Sales Bill Type","नगद/उधारो"],
          "debtor":["Debtor","डेव्टर"],
          "RefNo":["Ref. No","रिफरेन्स नं."],
          "salesOrderNo":["Sls Order No.","बिक्रि अादेश नं."],
          "Item":["Item","सामान"],
          "discount":["Discount","डिस्काउन्ट दर"],
          "discountAmt":["Discount Amt","डिस्काउन्ट रकम"],
          "totalCost":["Total Cost","जम्मा रकम"],
          "vat":["VAT (13%)","भ्याट (१३%)"],
          "netAmount":["Net Amount","नेट रकम"],
          "serviceCharge":["Service Charge","सर्भिस चार्ज"]
        },
        "journal":{
            "menuTitle":["Journal Voucher","जर्नल भाैचर"],
            "formDesc":["Account Description","खाता बिवरण"],
            "voucherNumber":["Voucher No","भाैचर नं."],
            "accountNo":["Account No","खाता नं."],
            "accountDesc":["Account Desc","खाता बिवरण"],
            "narration":["Naration","न्यारेशन"],
            "debit":["Debit","डेबिट"],
            "credit":["Credit","क्रेडिट"],
            "total":["Total => ","जम्मा"],
            "dt":["Date (BS)","मिति (बि.सं.)"],
            "group": ["Group","समूह"]
        },
        "receipt":{
            "menuTitle":["Receipt Voucher","प्राप्ती भाैचर"],
            "formDesc":["Account Desc","खाता बिवरण"],
            "voucherNumber":["Voucher No","भाैचर नं."],
            "accountNo":["Account No","खाता नं."],
            "accountDesc":["Account Desc","खाता बिवरण"],
            "narration":["Naration","न्यारेशन"],
            "amount":["Amount","रकम"],
            "total":["Total => ","जम्मा"],
            "dt":["Date (BS)","मिति (बि.सं.)"],
            "cashbank":["Cash/Bank","नगद/बैंक"],
            "collector":["Marketing Repr.","बाजार प्रतिनिधि"],
            "chequeNo":["Cheque No","चेक नं."],
            "depositorInfo":["Depositor Info","जम्मा गर्नेको बिवरण"],
            "returnBillNo":["Return Bill No.","फिर्ता बिल नं."],
            "billType":["Bill Type","नगद/उधारो"],
            "salesBillNo":["Sales Bill No.","बिक्रि बिजक नं."]
        },
        "purchaseorder":{
            "menuTitle":["Purchase Order","खरिद अादेश"],
            "order_no":["Order No","अादेश नं."],
            "created_by":["User","युजर"],
            "ordered_to":["Ordered To","अादेश"],
            "order_date_bs":["Date (BS)","मिति (बि.सं.)"],
            "order_date_ad":["Date (AD)","मिति (इ.सं.)"],
            "ordered_to":["Supplier Name","सप्लयसको नाम"],
            "email_address":["Email Address","इमेल ठेगाना"],
            "is_email_sent":["Emailed?","इमेल पठाइयो ?"],
            "details":{
              "menuTitle":["Purchase Order Details","खरिद अादेश बिवरण"],
              "item_name":["Item Name","सामान"],
              "qty":["Qty","परिमाण"],
              "unit":["Unit","युनिट"],
              "rate":["Rate","दर"],
              "amount":["Amount","रकम"],
              "email":["Email","इमेल"]
            }
        },
        "payment":{
            "menuTitle":["Payment Voucher","भुक्तानी भाैचर"],
            "formDesc":["Account Desc","खाता बिवरण"],
            "voucherNumber":["Voucher No","भाैचर नं."],
            "accountNo":["Account No","एकाउन्ट नं."],
            "accountDesc":["Account Desc","एकाउन्ट बिवरण"],
            "narration":["Naration","न्यारेशन"],
            "amount":["Amount","रकम"],
            "total":["Total => ","जम्मा"],
            "dt":["Date (BS)","मिति (बि.सं.)"],
            "cashbank":["Cash/Bank","नगद/बैंक"],
            "collector":["Marketing Repr.","बाजार प्रतिनिधि"],
            "chequeNo":["Cheque No","चेक नं."],
            "receivers_detail":["Receiver Info","बुझिलिनेको बिवरण"],
            "depositorInfo":["Depositor Info","डिपोजिटर गर्नेको बिवरण"]
        }
    },
    "reports":{
        "menuTitle":["Reports","रिपोर्टस"],
        "trialBalance":{
          "menuTitle":["Trial Balance","सन्तुलन परिक्षण"],
          "groupCode":["Group/Sub-Group","समूह/उप-समूह"],
          "groupDesc":["Group/Sub-Group Desc","समूह/उप-समूह बिवरण"]
        },
        "balancesheet":{
          "menuTitle":["Balance Sheet","ब्यालेन्स-सिट"]
        },
        "pl":{
          "menuTitle":["Profit and Loss","नाफा-नोक्सान"]
        },
        "stocksummary":{
          "menuTitle":["Stock Summary", "स्टक माैज्दात"]
        },
        "stockledger":{
          "menuTitle":["Stock Ledger", "स्टक लेजर"]
        },
        "salesbook":{
          "menuTitle":["Sales Book", "बिक्रि किताब"]
        },
        "purchasebook":{
          "menuTitle":["Purchase Book","खरिद किताब"]
        },
        "cashcollection":{
          "menuTitle":["Daily Cash Collection Report","दैनिक नगद कलेक्सन बिवरण"]
        }
    },
    "rback":{
        "menuTitle":["User","युजर"]
    },
    "menumanager":{
        "menuTitle":["Menu Manager","मेनु म्यानेजर"]
    },
    "error":{
      "invalidAccoutNo":["Invalid Account No","गलत खाता नं."]
    }
  }
}